// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPzk_Oyzq1oOaSwwUssIOtWzkaHwtCs9o',
    appId: '1:505807893059:web:418247fbd4b05c443f9af6',
    messagingSenderId: '505807893059',
    projectId: 'flutter-firstapp-b2c32',
    authDomain: 'flutter-firstapp-b2c32.firebaseapp.com',
    storageBucket: 'flutter-firstapp-b2c32.appspot.com',
    measurementId: 'G-LKXLFXR3D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfET-jflYxQTaK0yjSr9mXfqibVgFlbGc',
    appId: '1:505807893059:android:b946d6882638c4883f9af6',
    messagingSenderId: '505807893059',
    projectId: 'flutter-firstapp-b2c32',
    storageBucket: 'flutter-firstapp-b2c32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQnXxL3MqLuyXiYpP3_ug2PD1pBAYOn5M',
    appId: '1:505807893059:ios:16e4175c9f12b84c3f9af6',
    messagingSenderId: '505807893059',
    projectId: 'flutter-firstapp-b2c32',
    storageBucket: 'flutter-firstapp-b2c32.appspot.com',
    iosClientId: '505807893059-h8f25hd9v0mkhqm289aj4p4n3dg1a434.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQnXxL3MqLuyXiYpP3_ug2PD1pBAYOn5M',
    appId: '1:505807893059:ios:1e5b6a6f53dab8cb3f9af6',
    messagingSenderId: '505807893059',
    projectId: 'flutter-firstapp-b2c32',
    storageBucket: 'flutter-firstapp-b2c32.appspot.com',
    iosClientId: '505807893059-219gf703481nqev46ua1nfno5b7krhas.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
